<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Hemalatha" failures="1" tests="6" name="Test" time="24.944" errors="0" timestamp="2022-10-23T08:42:59 IST">
  <testcase classname="mavenexecution.LoginModule1Test" name="Succesfullogin" time="1.943">
    <failure type="java.lang.AssertionError" message="expected [Login incorrect. Please try  ] but found [Login incorrect. Please try again]">
      <![CDATA[java.lang.AssertionError: expected [Login incorrect. Please try  ] but found [Login incorrect. Please try again]
at mavenexecution.LoginModule1Test.Succesfullogin(LoginModule1Test.java:68)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- Succesfullogin -->
  <testcase classname="mavenexecution.LoginModule1Test" name="forgetpassword" time="1.536"/>
  <testcase classname="mavenexecution.REGESTRATIONMODULETEST" name="ValidateLoginNameField1" time="4.324"/>
  <testcase classname="mavenexecution.REGESTRATIONMODULETEST" name="ValidateLoginNameField2" time="2.506"/>
  <testcase classname="mavenexecution.REGESTRATIONMODULETEST" name="ValidateLoginNameField3" time="2.545"/>
  <testcase classname="mavenexecution.REGESTRATIONMODULETEST" name="ValidateLoginNameField4" time="2.752"/>
</testsuite> <!-- Test -->
